version: '3'
services:
  container:
    container_name: "container"
    build:
      context: ..
      dockerfile: ./build/container/Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - ../:/fun-cloud-api
    env_file:
      - ../configs/container/dev.env
  auth:
    container_name: "auth"
    build:
      context: ../
      dockerfile: ./build/auth/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ..:/fun-cloud-api
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./auth/mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  redis:
    container_name: "redis"
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass fun-cloud
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
