settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: container
    path: .
    commands:
      install:
        status: true
        dir: cmd/container
      run:
        status: true
        method: /go/bin/container
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - .idea
        - vendor
        - docs
        - developments