settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: container
    path: .
    commands:
      install:
        status: true
        dir: cmd/container
      run:
        status: true
        method: /go/bin/container
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .idea
        - configs
        - scripts
        - deployments
  - name: cloudauth
    path: .
    commands:
      install:
        status: true
        dir: cmd/cloudauth
      run:
        status: true
        method: /go/bin/cloudauth
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .idea
        - internal/container
        - cmd/container
        - configs
        - scripts
        - deployments