settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: auth
    path: .
    commands:
      install:
        status: true
        dir: cmd/auth
      run:
        status: true
        method: /go/bin/auth
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .idea
        - .realize
        - internal/container
        - cmd/container
        - configs
        - scripts
        - deployments