language: go
sudo: false
go:
  - "1.11.x"
  - master

script:
    - go test -v ./...
    - go build -o server main.go

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: server
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_GO_VERSION =~ ^1\.11\.[0-9]+$

