FROM golang:1.13
EXPOSE 3000
WORKDIR /tmp
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl && \
        chmod +x ./kubectl
WORKDIR /ccms
COPY . .
RUN go get github.com/pilu/fresh
ENV KUBECTL_BINARY_PATH="/tmp/kubectl"
ENV KUBECTL_DEPLOYMENT_MANIFEST_PATH="/ccms/manifest/yaml/pod-deployment-template.yaml"
ENV KUBECTL_CONFIG_PATH="ccms/file/kubeconfig"
CMD ["fresh"]