version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=zJ6pF57r54JH
      - MYSQL_DATABASE=prac
    command: mysqld --character-set-server=utf8
