version: '3'
services:
  container:
    container_name: "container"
    build:
      context: ..
      dockerfile: ../build/container/Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    container_name: "redis"
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass fun-cloud
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
