version: '3'
services:
  ccms:
    container_name: "ccms"
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      REDIS_ADDRESS: redis
      REDIS_PASSWORD: ccms
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    container_name: "redis"
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ccms
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
